week-6-final-VMARIN
learn-academy-2022-bravo/week-6-assessment-VMMarin pull request #1
Opened 2022-05-09 14:12 UTC by VMMarin

2022-05-12 05:26 UTC, elysemontano requested changes
I need to see pseudocode for problem one in javascript challenges to continue this review.

2022-05-16 04:18 UTC, VMMarin commented
Requested changes have been submitted.

2022-05-16 15:15 UTC, elysemontano approved these changes
Last assessment is DONE (once merged of course 😀)!  Your interview answers were amazing and you crushed the rails section!  I would really recommend spending some time reviewing [javascript functions](https://github.com/learn-academy-2022-bravo/Syllabus/blob/main/javascript/functions.md) in the syllabus.  Knowing the syntax and why we utilize functions is going to be very important when you start interviewing.

2022-05-16 15:15 UTC, elysemontano commented on code-challenges.test.js
> +}
Logic and test looks good!

2022-05-16 15:15 UTC, elysemontano commented on code-challenges.test.js
> +  })
Does this pass your test?  Currently this does not look like it is a function so arr would be undefined.

2022-05-16 15:15 UTC, elysemontano commented on code-challenges.test.js
> +  return thisVariable**2
I have never heard of Math.hypot before, pretty cool!  Try to keep all of your code inside your function.  A function is there to be a reusable block of code that will provide a specific desired output.  Providing outputs outside the function may not have the same desired result.

2022-05-16 15:15 UTC, elysemontano commented on interview-questions.md
> +  Example of how to fix the issue
A model is created initially, but if you forgot to add the cohort_id when the model was initially created you would need to create a migration.

2022-05-16 15:15 UTC, elysemontano commented on interview-questions.md
> +- As a developer, I can create a class called Task.
These are all great developer stories.  User stories are usually geared more toward what the user experience will be vs what the developer will be creating.

2022-05-16 15:15 UTC, elysemontano commented on rails-commenting.rb
> +    # ---10) we're saying here that the paramters required to create a blog post are :title, :content
Great job on this section!

2022-05-16 16:02 UTC, merged